-- Inserción de 15 usuarios de prueba
INSERT INTO usuarios (email, nombre, telefono, ciudad, tipo_usuario) VALUES
('ana@mail.com', 'Ana Torres', '912345678', 'Santiago', 'adoptante'),
('benja@mail.com', 'Benjamín Soto', '912345679', 'Valparaíso', 'refugio'),
('carla@mail.com', 'Carla Ruiz', '912345680', 'Concepción', 'adoptante'),
('daniel@mail.com', 'Daniel Pino', '912345681', 'La Serena', 'adoptante'),
('elena@mail.com', 'Elena Rojas', '912345682', 'Temuco', 'adoptante'),
('felipe@mail.com', 'Felipe Díaz', '912345683', 'Antofagasta', 'adoptante'),
('gabriela@mail.com', 'Gabriela Muñoz', '912345684', 'Iquique', 'adoptante'),
('hector@mail.com', 'Héctor Silva', '912345685', 'Puerto Montt', 'refugio'),
('isabel@mail.com', 'Isabel Castro', '912345686', 'Rancagua', 'adoptante'),
('jorge@mail.com', 'Jorge Herrera', '912345687', 'Talca', 'adoptante'),
('karla@mail.com', 'Karla Fuentes', '912345688', 'Chillán', 'adoptante'),
('luis@mail.com', 'Luis González', '912345689', 'Copiapó', 'adoptante'),
('marcela@mail.com', 'Marcela Vargas', '912345690', 'Arica', 'adoptante'),
('nicolas@mail.com', 'Nicolás Peña', '912345691', 'Punta Arenas', 'adoptante'),
('olga@mail.com', 'Olga Salinas', '912345692', 'Quillota', 'admin');

-- Inserción de 30 mascotas de prueba (usuario_id entre 1 y 15)
INSERT INTO mascotas (nombre, especie, raza, edad_meses, genero, ubicacion, usuario_id, vacunado, esterilizado, entrenado, chip) VALUES
('Luna', 'perro', 'mestizo', 24, 'hembra', 'Santiago', 1, true, true, false, 'CHIP001'),
('Max', 'perro', 'labrador', 36, 'macho', 'Valparaíso', 2, true, false, true, 'CHIP002'),
('Milo', 'gato', 'siamés', 12, 'macho', 'Concepción', 3, true, false, false, 'CHIP003'),
('Nina', 'gato', 'persa', 18, 'hembra', 'La Serena', 4, true, true, false, 'CHIP004'),
('Rocky', 'perro', 'bulldog', 30, 'macho', 'Temuco', 5, true, false, true, 'CHIP005'),
('Simba', 'gato', 'angora', 8, 'macho', 'Antofagasta', 6, false, false, false, 'CHIP006'),
('Toby', 'perro', 'poodle', 20, 'macho', 'Iquique', 7, true, true, true, 'CHIP007'),
('Maya', 'gato', 'calico', 14, 'hembra', 'Puerto Montt', 8, true, false, false, 'CHIP008'),
('Coco', 'perro', 'beagle', 28, 'macho', 'Rancagua', 9, true, true, true, 'CHIP009'),
('Lola', 'gato', 'azul ruso', 10, 'hembra', 'Talca', 10, false, false, false, 'CHIP010'),
('Bruno', 'perro', 'pastor alemán', 40, 'macho', 'Chillán', 11, true, true, true, 'CHIP011'),
('Mimi', 'gato', 'británico', 16, 'hembra', 'Copiapó', 12, true, false, false, 'CHIP012'),
('Duke', 'perro', 'dálmata', 22, 'macho', 'Arica', 13, true, false, true, 'CHIP013'),
('Kira', 'gato', 'maine coon', 26, 'hembra', 'Punta Arenas', 14, true, true, false, 'CHIP014'),
('Rex', 'perro', 'rottweiler', 34, 'macho', 'Quillota', 15, true, false, true, 'CHIP015'),
('Sasha', 'gato', 'bengalí', 11, 'hembra', 'Santiago', 1, false, false, false, 'CHIP016'),
('Zeus', 'perro', 'boxer', 25, 'macho', 'Valparaíso', 2, true, true, true, 'CHIP017'),
('Nala', 'gato', 'siamés', 13, 'hembra', 'Concepción', 3, true, false, false, 'CHIP018'),
('Thor', 'perro', 'bulldog', 29, 'macho', 'La Serena', 4, true, true, true, 'CHIP019'),
('Bella', 'gato', 'persa', 17, 'hembra', 'Temuco', 5, true, false, false, 'CHIP020'),
('Jack', 'perro', 'labrador', 32, 'macho', 'Antofagasta', 6, true, true, true, 'CHIP021'),
('Maggie', 'gato', 'angora', 9, 'hembra', 'Iquique', 7, false, false, false, 'CHIP022'),
('Oscar', 'perro', 'poodle', 21, 'macho', 'Puerto Montt', 8, true, false, true, 'CHIP023'),
('Chispa', 'gato', 'calico', 15, 'hembra', 'Rancagua', 9, true, true, false, 'CHIP024'),
('Daisy', 'perro', 'beagle', 27, 'hembra', 'Talca', 10, true, false, true, 'CHIP025'),
('Leo', 'gato', 'azul ruso', 7, 'macho', 'Chillán', 11, false, false, false, 'CHIP026'),
('Tina', 'perro', 'pastor alemán', 38, 'hembra', 'Copiapó', 12, true, true, true, 'CHIP027'),
('Fiona', 'gato', 'británico', 19, 'hembra', 'Arica', 13, true, false, false, 'CHIP028'),
('Sam', 'perro', 'dálmata', 23, 'macho', 'Punta Arenas', 14, true, true, true, 'CHIP029'),
('Mora', 'gato', 'maine coon', 24, 'hembra', 'Quillota', 15, true, false, false, 'CHIP030');
